export default {
  RECEIVE_TX: 0,
  REQUEST_LATEST_BLOCK: 1,
  RECEIVE_LATEST_BLOCK: 2,
  REQUEST_BLOCKCHAIN: 3,
  RECEIVE_BLOCKCHAIN: 4,
  REQUEST_HOSTS: 5,
  RECEIVE_HOSTS: 6,
  RECEIVE_REVERSE_CONNECTION: 7,
  REQUEST_REVERSE_CONNECTION: 8,
  REQUEST_MEMPOOL: 9,
  RECEIVE_MEMPOOL: 10,
  RECEIVE_TEXT: 11,
};
